### ISSUE TITLE
how was database migration managed ?

### ISSUE THREAD

**Issue by csc221** [satellity/satellity#144]
Great work! Given an orm is not used, I wonder how do you manage data migration? 

For myself play with the code, how do you recommend I get some fake data to start with ?

**Comment by jadeydi** [comment]
You can find the [database schema](https://github.com/satellity/satellity/blob/master/internal/models/schema.sql) here. There is no data migration, I update the table manually. 

Maybe you can start from tests. don't need fake data.

**Comment by csc221** [comment]
thanks!  I'm curious, in case you manually update the schema,  how do you migrate the database already deployed ? sorry for noob question, new to golang/web.

**Comment by jadeydi** [comment]
You can see the history of `schema.sql`, then I use SQL to update database. e. g.: `alter users add column name default ''`

**Comment by jadeydi** [comment]
The data structure is not complicated, migration like Rails is good, but not necessary.

**Comment by csc221** [comment]
Got it, thanks, Keep up good work on Satellity !
