### ISSUE TITLE
Got error when first startup

### ISSUE THREAD

**Issue by LinuxSuRen** [satellity/satellity#24]
WebSocket connection to 'ws://localhost:34875/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

parcelRequire.node_modules/parcel-bundler/src/builtins/hmr-runtime.js | @ | hmr-runtime.js:29
-- | -- | --
  | newRequire | @ | src.a2b27638.js:47
  | (anonymous) | @ | src.a2b27638.js:81
  | (anonymous) | @ | src.a2b27638.js:120

**Comment by jadeydi** [comment]
Are you using docker? I'm not using docker in both development and production, you can run the project by `npm run dev` in local. 
By the way, I'm planning to remove group subscription keeps forum only.

**Comment by LinuxSuRen** [comment]
It’s still error when I execute it under my local computer.

**Comment by jadeydi** [comment]
Can you put the error logs here?

**Comment by LinuxSuRen** [comment]
I can only get the error from web console which already commented above.

**Comment by jadeydi** [comment]
I have updated lots in those days, you can update it first.  I think this is parcel's error, I'm using mac.

**Comment by LinuxSuRen** [comment]
OK, thanks for that @jadeydi. I'll try it.
