### ISSUE TITLE
help me pls. I am newbe

### ISSUE THREAD

**Issue by lambogreny** [satellity/satellity#27]
Proxy error: Could not proxy request /api/categories from localhost:3000 to http://localhost:4000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

I join your slack

**Comment by jadeydi** [comment]
You should start back-end too, you can find available commands here: https://github.com/satellity/satellity/blob/master/Makefile

I'll improve document recently.
